const fakeResponseObj = {
    filters: {
        ProductionType: [
            'Background',
            'Commercials',
            'Corporate',
            'Nature',
            'Product Videos',
            'Travel',
        ],
        Keyword: [
            'Building',
            'Calm',
            'Emotional',
            'Energetic',
            'Gentle',
            'Hopeful',
            'Inspirational',
            'Motivating',
            'Positive',
            'Reflective',
            'Soft',
            'Triumphant',
            'Uplifting',
        ],
        Alben: ['On The Rise'],
        Instrument: [
            'Bass (Electric)',
            'Brass',
            'Drums',
            'Guitar (Electric)',
            'Percussion',
            'Piano',
            'Strings',
            'Synthesizer',
        ],
        Style: [
            'Building',
            'Corporate/Technology',
            'Filmmusic',
            'Transportation',
        ],
    },
    searchCueIDs: [7100856],
    alben: {
        616: {
            albumID: 616,
            albumName: 'On The Rise',
            albumCover: 'https://api.createmusic.com/albumCovers/616_500.jpg',
            albumCoverSmall:
                'https://api.createmusic.com/albumCovers/616_200.jpg',
            releaseTime: 1565679744,
            cueIDs: [7100856],
        },
    },
    playlists: {
        2: {
            id: '2',
            name: 'Adventure',
            image_url:
                'https://api.createmusic.com/playlistImages/Adventure_1000.jpg',
            description:
                'This is an adventurous playlist with many adventury tracks!',
            cue_ids: [
                '31208',
                '31216',
                '51302',
                '51305',
                '55404',
                '63404',
                '63808',
                '6410',
                '68504',
                '68610',
                '69504',
                '7100046',
                '7100630',
                '7100638',
                '7100645',
                '7100705',
                '7100723',
                '7100741',
                '7100750',
                '7100855',
                '7100856',
            ],
            cueIDs: ['7100856'],
        },
    },
    cueData: {
        7100856: {
            albumName: 'On The Rise',
            cueStyles: [
                'Transportation',
                'Corporate/Technology',
                'Filmmusic',
                'Building',
            ],
            cueID: 7100856,
            cueIntensity: 550,
            cueProductionType: [
                'Commercials',
                'Corporate',
                'Nature',
                'Travel',
                'Product Videos',
                'Background',
            ],
            albumID: 616,
            cueReleasetime: 1565679744,
            cueIsMLM: 1,
            cueDescription:
                'With the electric guitar in the center, Sunrise Avenue builds to...',
            cueKeywords: [
                'Energetic',
                'Positive',
                'Uplifting',
                'Inspirational',
                'Calm',
                'Gentle',
                'Motivating',
                'Reflective',
                'Triumphant',
                'Hopeful',
                'Emotional',
                'Soft',
                'Building',
            ],
            cueName: 'Sunrise Avenue',
            cueInstruments: [
                'Bass (Electric)',
                'Brass',
                'Drums',
                'Guitar (Electric)',
                'Percussion',
                'Piano',
                'Strings',
                'Synthesizer',
            ],
            cueTempo: 75,
            _score: 21.864733,
            fullDuration: 135000,
            cuePreviewURL:
                'http://back.smartsound.com/previews/7100800/7100856.mp3',
            fullLengthPreview: 'example',
            waveformPreview:
                'https://preview.createmusic.com/waveform/7100800/7100856_original_full.png',
        },
    },
};
